name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Show pwd
      run: pwd
    - name: Show pwd
      run: apt-get update && apt-get install -y locales 
    - name: Show 3
      run: pwd
